// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNKki6Bb6sT56bQ_RuDFcHil3PIiTjzNo',
    appId: '1:532595099404:android:556d15870c0350d31fab29',
    messagingSenderId: '532595099404',
    projectId: 'pixatalk-68492',
    storageBucket: 'pixatalk-68492.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgl1DR3Va2OEpDmoibWMV8EKRwwYi1eYU',
    appId: '1:532595099404:ios:c3bcabde17e817c31fab29',
    messagingSenderId: '532595099404',
    projectId: 'pixatalk-68492',
    storageBucket: 'pixatalk-68492.firebasestorage.app',
    androidClientId: '532595099404-hnok9kdgmckk423pl9fo3j2qr6ga0n2s.apps.googleusercontent.com',
    iosClientId: '532595099404-9ks22p4p7pu089nbmc6442g7n73e30tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

}